"use client";
import {useState} from "react";
import Link from "next/link";
import {pipelineScenarios,skillFields,skillMarkdown,validateSkill,type SkillDraft,type Variant} from "@/lib/ai-academy-advanced-labs";
const empty:SkillDraft={name:"",description:"",trigger:"",inputs:"",steps:"",output:"",validation:"",safety:""};
export function AdvancedPlayground({mode}:{mode:"skill"|"pipeline"}){
 const [draft,setDraft]=useState<SkillDraft>(empty),[variant,setVariant]=useState<Variant>("original"),[stage,setStage]=useState(0),[copyState,setCopyState]=useState("");
 const assessment=validateSkill(draft),scenario=pipelineScenarios[variant];
 async function copy(){try{await navigator.clipboard.writeText(skillMarkdown(draft));setCopyState("Copied draft. Review it before using in Cursor.");}catch{setCopyState("Copy unavailable. Select and copy the text manually.");}}
 return <main className="mx-auto w-full max-w-4xl px-5 py-12 sm:px-8"><Link className="text-sm text-accent underline" href="/ai-academy/playground">← All labs</Link>
 <p className="mt-8 text-xs font-semibold uppercase tracking-[.2em] text-accent">AI Academy / Intermediate practice</p>
 <h1 className="font-display mt-3 text-4xl sm:text-5xl">{mode==="skill"?"Build a Skill":"Research Pipeline Simulator"}</h1>
 {mode==="skill"?<section className="mt-7 space-y-6">
 <p className="leading-7 text-muted">Turn a repeated research task into a structured, inspectable skill draft. This creates text only: no agents run and no files are written to GitHub.</p>
 <div className="grid gap-4 sm:grid-cols-2">{skillFields.map(f=><label key={f.key} className="text-sm font-semibold">{f.label}<span className="mt-1 block text-xs font-normal text-muted">{f.hint}</span><textarea value={draft[f.key]} onChange={e=>{setDraft(v=>({...v,[f.key]:e.target.value}));setCopyState("")}} rows={3} className="mt-2 w-full rounded-lg border border-border bg-card p-3 font-normal" /></label>)}</div>
 <div role="status" aria-live="polite" className="rounded-lg border border-border bg-card p-4"><p className="font-semibold">{assessment.ready?"Draft structure complete":"Draft needs work"}</p><p className="mt-2 text-sm">{assessment.missing.length?`Missing: ${assessment.missing.join(", ")}`:"All eight fields have content."}</p>{!assessment.nameValid&&<p className="mt-1 text-sm">Use a lower-case, hyphenated name such as source-verification.</p>}</div>
 <section><h2 className="text-lg font-semibold">SKILL.md preview</h2><pre className="mt-3 max-h-96 overflow-auto whitespace-pre-wrap break-words rounded-lg bg-card p-5 text-xs leading-6">{skillMarkdown(draft)}</pre></section>
 <div className="flex flex-wrap gap-3"><button type="button" disabled={!assessment.ready} onClick={copy} className="rounded-lg bg-accent px-4 py-2 font-semibold text-accent-foreground disabled:opacity-50">Copy skill draft</button><button type="button" onClick={()=>{setDraft(empty);setCopyState("")}} className="rounded-lg border border-border px-4 py-2">Reset</button></div><p role="status" aria-live="polite" className="text-sm text-muted">{copyState}</p>
 <p className="text-sm text-muted">Next: open Cursor, create a skill folder, save as SKILL.md, test normal and edge cases, then commit through a pull request. Treat this as a teaching template, not a formally validated agent package.</p>
 </section>:<section className="mt-7 space-y-5"><p className="leading-7 text-muted">Explore the difference between a source, a captured version, evidence and a reviewed claim using synthetic examples. No network or database calls occur.</p>
 <label className="block text-sm font-semibold" htmlFor="case">Choose a capture scenario</label><select id="case" value={variant} onChange={e=>{setVariant(e.target.value as Variant);setStage(0)}} className="w-full rounded-lg border border-border bg-card p-3">{(Object.keys(pipelineScenarios) as Variant[]).map(id=><option value={id} key={id}>{pipelineScenarios[id].label}</option>)}</select>
 <p>{scenario.summary}</p><div className="grid gap-2 sm:grid-cols-4">{scenario.stages.map((s,i)=><button type="button" key={s.label} aria-pressed={stage===i} onClick={()=>setStage(i)} className={`rounded-lg border p-3 text-left text-sm ${stage===i?"border-accent bg-card":"border-border"}`}><span className="block text-xs text-muted">Step {i+1}</span><strong>{s.label}</strong></button>)}</div>
 <article className="rounded-lg border border-border bg-card p-6" aria-live="polite"><p className="text-xs uppercase tracking-widest text-accent">Step {stage+1} of 4</p><h2 className="mt-2 text-2xl font-semibold">{scenario.stages[stage].label}</h2><p className="mt-3">{scenario.stages[stage].description}</p><p className="mt-4 font-semibold">{scenario.stages[stage].outcome}</p></article><div className="flex flex-wrap gap-3"><button type="button" onClick={()=>setStage(s=>(s+1)%4)} className="rounded-lg bg-accent px-4 py-2 font-semibold text-accent-foreground">Next step →</button><button type="button" onClick={()=>setStage(0)} className="rounded-lg border border-border px-4 py-2">Reset</button></div><p className="rounded-lg bg-card p-4 text-sm"><strong>What matters:</strong> {scenario.decision}</p></section>}
 <p className="mt-9 text-xs text-muted">Practice only. Fixtures are fictional and don't establish facts about real companies.</p></main>
}
