"use client";
import {useState} from "react";
import Link from "next/link";
import {assessCase,assessEvidence,detectiveCases,evidenceLessons,reviewPrompt,promptFields,recommendApproach} from "@/lib/ai-academy-labs";
const outline="rounded-lg border border-border bg-card px-4 py-2 text-left focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-accent";
export function Playground(){
 const [lab,setLab]=useState<"detective"|"prompt"|"selector">("detective");
 const [scenario,setScenario]=useState(0);
 const [answer,setAnswer]=useState<number|null>(null); const [evidence,setEvidence]=useState<number|null>(null);
 const [submitted,setSubmitted]=useState(false);
 const [fields,setFields]=useState<Record<string,string>>({});
 const [task,setTask]=useState<"writing"|"research"|"code">("research");
 const [sensitive,setSensitive]=useState(false);const [offline,setOffline]=useState(false);
 const c=detectiveCases[scenario],feedback=answer===null?null:assessCase(c.id,answer),result=reviewPrompt(fields),recommendation=recommendApproach(task,sensitive,offline);
 const prompt=promptFields.map(f=>`${f}: ${fields[f]||"[add details]"}`).join("\n");
 return <main className="mx-auto w-full max-w-5xl px-5 py-12 sm:px-8">
 <p className="text-xs font-semibold uppercase tracking-[.2em] text-accent">AI Academy / Practice</p>
 <h1 className="font-display mt-3 text-5xl">AI Playground</h1>
 <p className="mt-3 max-w-2xl text-muted">Practice a skill with fictional scenarios and transparent feedback. No AI provider calls, tracking, saved answers or accounts required.</p>
 <section className="mt-7 rounded-xl border border-accent bg-card p-5"><p className="text-xs font-semibold uppercase tracking-widest text-accent">Recommended first journey</p><h2 className="mt-2 text-xl font-semibold">Learn → Practice → Feedback → Apply</h2><p className="mt-2 text-sm leading-6 text-muted">Follow a guided source-verification lesson, test your reasoning, and connect it to Account Intelligence using fictional evidence.</p><Link href="/ai-academy/journeys/source-verification" className="mt-3 inline-block rounded-lg bg-accent px-4 py-2 text-sm font-semibold text-accent-foreground">Start source verification journey →</Link></section>
 <nav aria-label="Playground labs" className="mt-8 flex flex-wrap gap-2">
 {([["detective","Source Detective"],["prompt","Prompt Studio"],["selector","Tool Selector"]] as const).map(([id,label])=><button type="button" key={id} aria-pressed={lab===id} onClick={()=>setLab(id)} className={`${outline} ${lab===id?"border-accent bg-foreground text-background":""}`}>{label}</button>)}
 </nav>
 {lab==="detective"&&<section className="mt-8 rounded-xl border border-border bg-card p-5 sm:p-8" aria-labelledby="source-title">
 <p className="text-xs uppercase tracking-widest text-accent">Lab 01 · Evidence & trust · Fictional case {scenario+1} of {detectiveCases.length}</p>
 <h2 id="source-title" className="font-display mt-2 text-3xl">{c.title}</h2><p className="mt-2 text-sm text-muted">{c.domain}</p>
 <div className="mt-6 rounded-lg bg-background p-5"><p className="text-xs font-semibold uppercase tracking-wider text-muted">AI-generated claim</p><p className="mt-2 text-lg font-semibold">{c.claim}</p></div>
 <h3 className="mt-7 font-semibold">Inspect the evidence</h3><div className="mt-3 grid gap-3 md:grid-cols-2">{c.sources.map(s=><article key={s.name} className="rounded-lg border border-border p-4"><p className="text-sm font-semibold">{s.name}</p><p className="mt-1 text-xs text-muted">Captured {s.date} · Synthetic teaching fixture</p><blockquote className="mt-3 border-l-2 border-accent pl-3 text-sm leading-7">{s.text}</blockquote></article>)}</div>
 <fieldset className="mt-7"><legend className="font-semibold">What's the best assessment?</legend><div className="mt-3 space-y-2">{c.options.map((opt,i)=><label key={opt} className="flex cursor-pointer gap-3 rounded-lg border border-border p-3 text-sm"><input type="radio" name={c.id} checked={answer===i} onChange={()=>{setAnswer(i);setSubmitted(false)}} className="accent-accent"/>{opt}</label>)}</div></fieldset>
 <fieldset className="mt-6"><legend className="font-semibold">{evidenceLessons[c.id].question}</legend><p className="mt-1 text-sm text-muted">Select one passage you would inspect first. This is a separate skill from classifying the claim.</p><div className="mt-3 space-y-2">{c.sources.map((src,i)=><label key={src.name} className="flex gap-3 rounded-lg border border-border p-3 text-sm"><input type="radio" name={c.id+"-evidence"} checked={evidence===i} onChange={()=>{setEvidence(i);setSubmitted(false)}} className="accent-accent"/>{src.name}</label>)}</div></fieldset>
 <div className="mt-5 flex flex-wrap gap-3"><button type="button" disabled={answer===null||evidence===null} onClick={()=>setSubmitted(true)} className="rounded-lg bg-accent px-5 py-3 font-semibold text-accent-foreground disabled:opacity-50">Check assessment</button><button type="button" onClick={()=>{setAnswer(null);setEvidence(null);setSubmitted(false)}} className={outline}>Reset</button></div>
 {submitted&&feedback&&<div role="status" className="mt-5 rounded-lg bg-background p-5"><h3 className="font-semibold">{feedback.correct&&assessEvidence(c.id,evidence??-1)?.correct?"Both steps correct":"Review your classification and selected evidence"}</h3><p className="mt-2 text-sm leading-7">{feedback.explanation}</p><p className="mt-2 text-sm"><strong>Evidence feedback:</strong> {evidenceLessons[c.id].rationale}</p><p className="mt-2 text-sm"><strong>Common misconception:</strong> {evidenceLessons[c.id].misconception}</p><p className="mt-2 text-sm"><strong>Apply this:</strong> {evidenceLessons[c.id].transfer}</p><p className="mt-2 text-sm"><strong>Next:</strong> {feedback.next}</p></div>}
 <div className="mt-7 flex flex-wrap gap-3 border-t border-border pt-5"><button type="button" className={outline} onClick={()=>{setScenario((scenario+1)%detectiveCases.length);setAnswer(null);setEvidence(null);setSubmitted(false)}}>Next fictional case →</button><Link href="/ai-academy" className="self-center text-sm text-accent underline">Back to AI Foundations</Link></div>
 </section>}
 {lab==="prompt"&&<section className="mt-8 rounded-xl border border-border bg-card p-5 sm:p-8"><p className="text-xs uppercase tracking-widest text-accent">Lab 02 · Prompt fundamentals</p><h2 className="font-display mt-2 text-3xl">Prompt Studio</h2><p className="mt-3 text-muted">Build a clear request for a fictional account research brief. Complete six parts, then inspect your draft. This checks completeness, not actual answer quality.</p><div className="mt-6 grid gap-4 md:grid-cols-2">{promptFields.map(f=><label key={f} className="block text-sm font-semibold">{f}<textarea value={fields[f]||""} onChange={e=>setFields(v=>({...v,[f]:e.target.value}))} rows={3} className="mt-2 block w-full resize-y rounded-lg border border-border bg-background p-3 font-normal" placeholder={f==="Objective"?"e.g., Prepare a sourced account brief":`Describe ${f.toLowerCase()}`}/></label>)}</div><p aria-live="polite" className="mt-5 text-sm">{result.score} / 6 sections completed. {result.complete?"All required sections provided.":"Missing: "+result.missing.join(", ")}</p><div className="mt-5 rounded-lg bg-background p-4"><h3 className="font-semibold">Your draft</h3><pre className="mt-3 whitespace-pre-wrap break-words font-sans text-sm leading-6">{prompt}</pre></div><p className="mt-3 text-sm text-muted">Completeness is not quality. Independently verify accuracy, privacy, and usefulness.</p>{result.warnings.length>0&&<ul className="mt-2 list-disc pl-5 text-sm text-muted">{result.warnings.map(w=><li key={w}>{w}</li>)}</ul>}<div className="mt-4 flex gap-3"><button type="button" onClick={()=>navigator.clipboard.writeText(prompt).catch(()=>{})} className="rounded-lg bg-accent px-4 py-2 text-sm font-semibold text-accent-foreground">Copy draft</button><button type="button" onClick={()=>setFields({})} className={outline}>Reset</button></div></section>}
 {lab==="selector"&&<section className="mt-8 rounded-xl border border-border bg-card p-5 sm:p-8"><p className="text-xs uppercase tracking-widest text-accent">Lab 03 · Task-first decisions</p><h2 className="font-display mt-2 text-3xl">Model & Tool Selector</h2><p className="mt-3 text-muted">Choose a workflow based on task requirements before considering vendor names. These are transparent starter rules, not benchmarks.</p><div className="mt-6 space-y-5"><label className="block text-sm font-semibold">What are you doing?<select className="mt-2 block w-full rounded-lg border border-border bg-background p-3" value={task} onChange={e=>setTask(e.target.value as typeof task)}><option value="research">Source-backed research</option><option value="writing">Drafting / writing</option><option value="code">Editing a software repository</option></select></label><label className="flex gap-3 text-sm"><input type="checkbox" checked={sensitive} onChange={e=>setSensitive(e.target.checked)}/>The task includes sensitive or unapproved company information</label><label className="flex gap-3 text-sm"><input type="checkbox" checked={offline} onChange={e=>setOffline(e.target.checked)}/>Must work without external network access</label></div><div role="status" className="mt-7 rounded-lg bg-background p-5"><h3 className="text-xl font-semibold">{recommendation.title}</h3><p className="mt-3 text-sm leading-7">{recommendation.why}</p><p className="mt-3 text-sm"><strong>Validate:</strong> {recommendation.validation}</p></div></section>}
 <section className="mt-10 border-t border-border pt-7"><h2 className="font-display text-2xl">Keep building</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><Link href="/ai-academy/playground/skill-builder" className="rounded-xl border border-border bg-card p-5 hover:border-accent"><strong className="block">Build a Skill →</strong><span className="mt-2 block text-sm text-muted">Create a reusable SKILL.md draft from a repeatable task.</span></Link><Link href="/ai-academy/playground/research-pipeline" className="rounded-xl border border-border bg-card p-5 hover:border-accent"><strong className="block">Research Pipeline Simulator →</strong><span className="mt-2 block text-sm text-muted">Explore capture, versions, evidence, conflict and review.</span></Link></div></section>
 <p className="mt-8 text-xs leading-6 text-muted">All examples are fictional. Exercises do not perform live verification and are not evidence of real vendor capabilities, purchasing intent or security compliance.</p>
 </main>;
}
