"use client";
import {useState} from "react";
import Link from "next/link";
import {evaluatePrompt,fictionalSources,generatePracticePrompt,improvedExample,promptJourneySteps,promptLabels,promptParts,starterPrompt,type PromptInput} from "@/lib/ai-prompt-journey";
const empty=Object.fromEntries(promptParts.map(p=>[p,""])) as PromptInput;
export function PromptJourney(){
 const [step,setStep]=useState(0),[draft,setDraft]=useState<PromptInput>(empty),[checked,setChecked]=useState(false),[reflection,setReflection]=useState(""),[complete,setComplete]=useState(false),[copyStatus,setCopyStatus]=useState("");
 const result=evaluatePrompt(draft);
 const btn="rounded-lg bg-accent px-5 py-3 font-semibold text-accent-foreground disabled:opacity-50";
 return <main className="mx-auto w-full max-w-4xl px-5 py-12 sm:px-8"><Link className="text-sm text-accent underline" href="/ai-academy/playground">← All labs</Link>
 <p className="mt-8 text-xs font-semibold uppercase tracking-[.2em] text-accent">AI Foundations / Guided journey</p><h1 className="font-display mt-3 text-4xl sm:text-5xl">Turn a vague prompt into a research workflow</h1><p className="mt-4 text-muted">Learn, practice, evaluate, and apply structured prompting with fictional account research. No model calls or data storage.</p>
 <nav aria-label="Journey steps" className="mt-8 grid grid-cols-2 gap-2 sm:grid-cols-4">{promptJourneySteps.map((label,i)=><div key={label} aria-current={step===i?"step":undefined} className={`rounded-lg border p-3 text-sm ${step===i?"border-accent bg-card":"border-border"}`}><span className="block text-xs text-muted">{i+1} of 4</span><strong>{label}</strong></div>)}</nav>
 {step===0&&<section className="mt-8 space-y-5 rounded-xl border border-border bg-card p-6"><h2 className="font-display text-3xl">Why prompts need structure</h2><div className="rounded-lg bg-background p-4"><p className="text-xs text-muted">Before</p><p className="mt-2 font-semibold">{starterPrompt}</p></div><p>A model could invent buying intent because the task provides neither evidence nor a validation standard. A stronger request specifies six things: objective, audience, sources, constraints, format, and validation.</p><div className="grid gap-3 sm:grid-cols-2">{promptParts.map(part=><div key={part} className="rounded-lg border border-border p-3"><strong>{promptLabels[part]}</strong><p className="mt-1 text-sm text-muted">{improvedExample[part]}</p></div>)}</div><p className="text-sm text-muted">A well-structured prompt does not guarantee a correct answer; factual checks still matter.</p><button className={btn} onClick={()=>setStep(1)}>Practice →</button></section>}
 {step===1&&<section className="mt-8 space-y-5 rounded-xl border border-border bg-card p-6"><h2 className="font-display text-3xl">Build your prompt</h2><p>Use these fictional excerpts to prepare an AE research task. Don't infer that Acme is purchasing security software.</p><div className="grid gap-3 sm:grid-cols-2">{fictionalSources.map(s=><div key={s.name} className="rounded-lg bg-background p-4"><strong>{s.name}</strong><p className="mt-2 text-sm">{s.text}</p></div>)}</div><div className="grid gap-4 sm:grid-cols-2">{promptParts.map(part=><label key={part} className="block text-sm font-semibold">{promptLabels[part]}<textarea rows={3} value={draft[part]} onChange={e=>{setDraft(d=>({...d,[part]:e.target.value}));setChecked(false)}} className="mt-2 w-full rounded-lg border border-border bg-background p-3 font-normal" placeholder={improvedExample[part]}/></label>)}</div><div className="flex flex-wrap gap-3"><button className={btn} onClick={()=>{setChecked(true);setStep(2)}}>Evaluate draft →</button><button className="rounded-lg border border-border px-4 py-2" onClick={()=>setDraft(improvedExample)}>Load worked example</button></div></section>}
 {step===2&&checked&&<section aria-live="polite" className="mt-8 space-y-5 rounded-xl border border-border bg-card p-6"><h2 className="font-display text-3xl">{result.ready?"Your prompt meets the practice rubric":"Your prompt needs another pass"}</h2><p className="text-sm text-muted">This is a transparent structural and safeguard check—not AI-based grading and not proof of factual quality.</p><p><strong>Sections requiring detail:</strong> {result.missing.length?result.missing.map(k=>promptLabels[k]).join(", "):"None"}</p><ul className="list-disc space-y-2 pl-5 text-sm">{result.warnings.map(w=><li key={w}>{w}</li>)}</ul><div className="rounded-lg bg-background p-4"><h3 className="font-semibold">Your resulting prompt</h3><pre className="mt-3 whitespace-pre-wrap break-words font-sans text-sm">{generatePracticePrompt(draft)}</pre></div><div className="flex flex-wrap gap-3"><button className="rounded-lg border border-border px-4 py-2" onClick={()=>setStep(1)}>Revise draft</button><button disabled={!result.ready} className={btn} onClick={()=>setStep(3)}>Apply it →</button></div></section>}
 {step===3&&result.ready&&<section className="mt-8 space-y-5 rounded-xl border border-border bg-card p-6"><h2 className="font-display text-3xl">Apply it to account intelligence</h2><p>Your Account Signal Engine can collect sources, preserve versions, and support a cited brief. The prompt helps you specify what the research must demonstrate, but it is not an actual research execution.</p><label className="block text-sm font-semibold">What would you verify before sharing the brief?<textarea rows={3} value={reflection} onChange={e=>setReflection(e.target.value)} className="mt-2 w-full rounded-lg border border-border bg-background p-3 font-normal" placeholder="I'd confirm every buying signal against a dated primary source..."/></label><div className="flex flex-wrap gap-3"><button disabled={reflection.trim().length<12} className={btn} onClick={()=>setComplete(true)}>Complete practice journey</button><button className="rounded-lg border border-border px-4 py-2" onClick={async()=>{try{await navigator.clipboard.writeText(generatePracticePrompt(draft));setCopyStatus("Prompt copied.");}catch{setCopyStatus("Copy unavailable; select text in the feedback step.");}}}>Copy prompt</button></div><p role="status" className="text-sm">{copyStatus}</p>{complete&&<div role="status" className="rounded-lg bg-background p-4"><strong>Practice completed in this session.</strong><p className="mt-2 text-sm">Your reflection is not graded or saved. For the next skill, explore the Source Verification journey.</p><Link href="/ai-academy/journeys/source-verification" className="mt-3 inline-block text-accent underline">Practice Source Detective →</Link></div>}</section>}
 <p className="mt-8 text-xs text-muted">Synthetic teaching fixtures only. Completion isn't formal certification; no network or model calls.</p></main>;
}
