export type SkillDraft={name:string;description:string;trigger:string;inputs:string;steps:string;output:string;validation:string;safety:string};
export const skillFields: {key:keyof SkillDraft; label:string; hint:string}[]=[
{key:"name",label:"Skill name",hint:"lowercase-hyphen-name"},
{key:"description",label:"Purpose",hint:"What problem does it solve?"},
{key:"trigger",label:"When to use",hint:"What task should trigger it?"},
{key:"inputs",label:"Required inputs",hint:"What must the user provide?"},
{key:"steps",label:"Procedure",hint:"Numbered steps and source checks"},
{key:"output",label:"Expected result",hint:"What should it produce?"},
{key:"validation",label:"Verification",hint:"How do you tell it worked?"},
{key:"safety",label:"Safety boundaries",hint:"What must it never do?"}
];
export function validateSkill(d:SkillDraft){const missing=skillFields.filter(f=>!d[f.key].trim()).map(f=>f.label);const nameValid=/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(d.name);return {missing,nameValid,ready:missing.length===0&&nameValid};}
export function skillMarkdown(d:SkillDraft){const name=/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(d.name)?d.name:"replace-with-valid-name";const desc=d.description.replace(/[\r\n]+/g," ").trim();return `---\nname: ${name}\ndescription: ${desc}\n---\n# ${name}\n\n## When to use\n${d.trigger}\n\n## Inputs\n${d.inputs}\n\n## Procedure\n${d.steps}\n\n## Output\n${d.output}\n\n## Validation\n${d.validation}\n\n## Safety boundaries\n${d.safety}\n`;}
export type Variant="original"|"duplicate"|"changed"|"contradiction"|"injection";
export type Stage={label:string;description:string;outcome:string};
export const pipelineScenarios:Record<Variant,{label:string;summary:string;stages:Stage[];decision:string}>={
original:{label:"Original capture",summary:"A new approved fictional product page is captured.",stages:[{label:"Source",description:"Canonicalize the approved public URL.",outcome:"1 source created"},{label:"Capture",description:"Store a fingerprint and source text.",outcome:"Version v1 created"},{label:"Evidence",description:"Match quotation to stored version text.",outcome:"Supporting quote linked to v1"},{label:"Review",description:"Human reviews the supported claim.",outcome:"Claim pending approval"}],decision:"Do not publish a claim before evidence review."},
duplicate:{label:"Same content again",summary:"A second capture returns identical normalized content.",stages:[{label:"Source",description:"Resolve canonical URL to existing identity.",outcome:"Same source"},{label:"Capture",description:"Compare SHA-256 fingerprints.",outcome:"Reuse v1, no duplicate version"},{label:"Evidence",description:"Keep existing anchors.",outcome:"Original support retained"},{label:"Review",description:"Record the latest successful check.",outcome:"No new claim required"}],decision:"An unchanged page still deserves a fresh check timestamp."},
changed:{label:"Meaningful change",summary:"A documented product limit changes in a new capture.",stages:[{label:"Source",description:"Keep same canonical identity.",outcome:"Same source"},{label:"Capture",description:"Different normalized content fingerprint.",outcome:"New immutable v2"},{label:"Evidence",description:"Reassess claims against v2.",outcome:"Previous claim needs review"},{label:"Review",description:"Compare old and new meaning.",outcome:"Human assesses significance"}],decision:"Hash changes alone cannot determine business significance."},
contradiction:{label:"Conflicting information",summary:"Two fictional documents offer incompatible claims.",stages:[{label:"Source",description:"Preserve publisher and document identities.",outcome:"Two distinct sources"},{label:"Capture",description:"Store both original passages.",outcome:"Separate source versions"},{label:"Evidence",description:"Link support and refutation separately.",outcome:"Conflicting evidence"},{label:"Review",description:"Flag uncertainty instead of deciding automatically.",outcome:"Needs review"}],decision:"Never silently choose the newest source as always correct."},
injection:{label:"Untrusted page instructions",summary:"A page contains a fake command to reveal secrets.",stages:[{label:"Source",description:"Fetch only allowlisted URLs.",outcome:"Source checked"},{label:"Capture",description:"Treat raw text as untrusted.",outcome:"Content stored as data"},{label:"Evidence",description:"Ignore commands embedded in source text.",outcome:"No tool instruction executed"},{label:"Review",description:"Flag malicious or irrelevant excerpt.",outcome:"Rejected as instructions"}],decision:"A retrieved webpage can provide evidence, never permission to override instructions."}
};
