export type Case = {id:string;title:string;domain:string;claim:string;sources:{name:string;date:string;text:string}[];options:string[];correct:number;explanation:string;next:string};
export const detectiveCases:Case[]=[
{id:"capabilities",title:"Vendor capability check",domain:"Security research",claim:"Acme Security supports every public cloud and guarantees perfect threat detection.",sources:[{name:"Fictional Acme product docs",date:"2026-01-10",text:"The platform collects telemetry from AWS and Azure."},{name:"Fictional Acme marketing",date:"2026-01-12",text:"Our platform helps teams improve detection coverage."}],options:["Verified","Unsupported / overstated","Proven completely false"],correct:1,explanation:"The evidence documents AWS and Azure only, and never guarantees 100% detection. An unsupported universal claim is not necessarily definitively disproven.",next:"Check whether a claim is fully supported rather than extrapolating."},
{id:"signal",title:"Buying signal or hypothesis?",domain:"GTM intelligence",claim:"Acme's $30M financing means it has approved a cybersecurity software budget.",sources:[{name:"Fictional Acme press announcement",date:"2026-02-07",text:"Acme announced a $30M funding round to expand product development and hiring."},{name:"Fictional investor summary",date:"2026-02-08",text:"The funding will support growth initiatives. No security procurement plans were announced."}],options:["Verified spending decision","Plausible but unverified hypothesis","Definitely no security spending"],correct:1,explanation:"Funding may be a reason to investigate, but it is not evidence of an approved security purchase.",next:"Write a discovery question instead of stating buying intent."},
{id:"change",title:"Documentation change investigation",domain:"Source versioning",claim:"A changed document hash proves the vendor launched a new capability.",sources:[{name:"Synthetic snapshot v1",date:"2026-03-01",text:"Endpoint alerts can be exported to CSV."},{name:"Synthetic snapshot v2",date:"2026-03-05",text:"Endpoint alerts can be exported to CSV. (Updated punctuation and heading.)"}],options:["Yes, hash change proves a new feature","No, this is an editorial-only change","Insufficient evidence to tell that the text changed"],correct:1,explanation:"The example changes editorial text, not the capability. A content hash signals changed bytes, not business importance.",next:"Separate raw diff detection from semantic significance."}
];
export function assessCase(id:string,answer:number){const c=detectiveCases.find(x=>x.id===id);if(!c)return null;return {correct:answer===c.correct,explanation:c.explanation,next:c.next};}
export function recommendApproach(task:"writing"|"research"|"code",sensitive:boolean,offline:boolean){if(sensitive)return {title:"Use an approved private workflow",why:"Verify workspace permission, retention and data controls before processing sensitive information.",validation:"Confirm policy, authorization and minimal required inputs."};if(offline)return {title:"Use local tools or a deterministic exercise",why:"Offline requirements rule out web retrieval and hosted inference.",validation:"Test using locally available files and fixtures."};if(task==="research")return {title:"Use source-backed research and verification",why:"A research task requires original evidence, source dates and uncertainty checks.",validation:"Open cited pages and confirm each material claim."};if(task==="code")return {title:"Use a repository-aware coding assistant",why:"Tests, dependency context and Git changes matter for code tasks.",validation:"Review diffs, run tests and inspect access rights."};return {title:"Start with a well-structured prompt",why:"A narrow writing task may not need agents or retrieval.",validation:"Check clarity, factual claims and intended audience."};}
export const promptFields=["Objective","Audience","Context / sources","Constraints","Output format","Validation"] as const;
export function promptCompleteness(data:Record<string,string>){const missing=promptFields.filter(x=>!data[x]?.trim());return {missing,complete:missing.length===0,score:promptFields.length-missing.length};}
