export const promptJourneySteps=["Learn","Practice","Feedback","Apply"] as const;
export const starterPrompt="Research Acme Security and tell me if they're buying security software.";
export const improvedExample={objective:"Prepare a fictional account research brief identifying confirmed company developments.",audience:"Enterprise AE preparing discovery.",sources:"Use only the two fictional excerpts provided in this exercise; cite the excerpt supporting each factual statement.",constraints:"Do not claim approved budget or purchase intent without explicit evidence. Label hypotheses.",format:"Separate Verified facts, Hypotheses, Unknowns and Discovery questions.",validation:"For each fact, point to a source excerpt. Mark unsupported items unknown."};
export type PromptInput=typeof improvedExample;
export const promptParts=(Object.keys(improvedExample) as (keyof PromptInput)[]);
export const promptLabels:Record<keyof PromptInput,string>={objective:"Objective",audience:"Audience",sources:"Sources and context",constraints:"Constraints",format:"Output format",validation:"Validation"};
export function evaluatePrompt(input:PromptInput){const missing=promptParts.filter(key=>input[key].trim().length<12);const warnings:string[]=[];if(/guarantee|100%|never hallucinate/i.test(Object.values(input).join(" ")))warnings.push("Absolute performance guarantees cannot replace evidence checks.");if(!/cite|source|excerpt|reference|quote/i.test(input.validation))warnings.push("Specify how factual statements are checked against sources.");if(!/hypothes|unknown|uncertain|unsupported|do not infer/i.test(input.constraints+" "+input.format))warnings.push("Explicitly distinguish evidence from speculation.");return {missing,warnings,ready:missing.length===0&&warnings.length===0};}
export const fictionalSources=[{name:"Fictional press release",text:"Acme announced a $30 million funding round to expand product development and hiring."},{name:"Fictional hiring announcement",text:"Acme is recruiting two software engineers and a product designer."}];
export function generatePracticePrompt(input:PromptInput){return promptParts.map(p=>`${promptLabels[p]}: ${input[p].trim()||"[not supplied]"}`).join("\n\n");}
